112 integrate interface into mensahub
olech2412/MensaHub pull request #141
Opened 2024-08-09 19:41 UTC by whosFritz

Änderung nach dem Video noch gemacht:
- User bekommt notification wenn das rating erfolgreich war

https://github.com/user-attachments/assets/a45af368-d017-44e4-94d3-9ded93e1c164

Veränderungen:
- komplett neuer activation view mit Bewertungen für den User die er bei seinen abonnierten Mensas machen muss (top 20 Gerichte) (kein Gouda)
- kein @Autowire
- kein repository (Datenbank) im frontend genutzt (Anti Jonas Pohl)

BITTE MAL KOMPLETTEN CODE DURCHGEHEN

closes #112

2024-08-12 12:59 UTC, olech2412 requested changes
Siehe Kommentare, eigentlich alles drin

2024-08-12 12:59 UTC, olech2412 commented on MensaHub-Models/src/main/java/de/olech2412/mensahub/models/authentification/MailUser.java
Dafür muss die MensaHub-Models Version auf 2.1.2 angehoben werden

2024-08-12 12:59 UTC, olech2412 commented on MensaHub-Junction/src/main/java/de/olech2412/mensahub/junction/jpa/services/meals/MealsService.java
> +        return mealRepository.findTop20DistinctMealsExcludingGoudaByUser(userId);
Das ist für jetzt okay. Wir sollten diese Woche aber unbedingt mal die Top 20 Gerichte durchgucken und uns dann ein Regex bauen, was die meisten berücksichtigt. Es gibt auch Spirelli und Bandnudeln und sowas... Das ist bisschen scuffed über diese massive SQL Query. Sind ja auch nicht allzu viele Daten, also sollte ein simpler Stream easy reichen.

2024-08-12 12:59 UTC, olech2412 commented on MensaHub-Junction/src/main/java/de/olech2412/mensahub/junction/jpa/repository/meals/MealRepository.java
Das ist für jetzt okay. Wir sollten diese Woche aber unbedingt mal die Top 20 Gerichte durchgucken und uns dann ein Regex bauen, was die meisten berücksichtigt. Es gibt auch Spirelli und Bandnudeln und sowas... Das ist bisschen scuffed über diese massive SQL Query. Sind ja auch nicht allzu viele Daten, also sollte ein simpler Stream easy reichen.

2024-08-12 12:59 UTC, olech2412 commented on MensaHub-Junction/pom.xml
> +        <!-- Vaadin Addons -->
Benutzt du das, habe keinen Import davon gefunden...?

2024-08-12 12:59 UTC, olech2412 commented on MensaHub-Junction/src/main/java/de/olech2412/mensahub/junction/jpa/repository/meals/MealRepository.java
Vllt. please noch in diesem PR fixen so mäßig, aber halt als stream und dann raussortieren: https://www.w3schools.com/java/java_regex.asp

2024-08-12 12:59 UTC, olech2412 commented on MensaHub-Junction/src/main/java/de/olech2412/mensahub/junction/jpa/services/meals/MealsService.java
> +        return mealRepository.findTop20DistinctMealsExcludingGoudaByUser(userId);
Vllt. please noch in diesem PR fixen so mäßig, aber halt als stream und dann raussortieren: https://www.w3schools.com/java/java_regex.asp

2024-08-12 12:59 UTC, olech2412 commented on MensaHub-Junction/src/main/java/de/olech2412/mensahub/junction/gui/views/ActivationView.java
Nicht mobile responsive: 
![image](https://github.com/user-attachments/assets/4d7b570a-c59a-4e85-ae0e-cdcd3bb64ffe)

2024-08-12 12:59 UTC, olech2412 commented on MensaHub-Junction/src/main/java/de/olech2412/mensahub/junction/gui/views/ActivationView.java
Aktivierungscode erst löschen, sobald alle 20 Bewertungen abgegeben wurden. Ansonsten ist eine Bewertung nicht möglich, sobald der User einmal refreshed

2024-08-12 12:59 UTC, olech2412 commented on MensaHub-Junction/src/main/java/de/olech2412/mensahub/junction/gui/views/ActivationView.java
Vielleicht am Ende, wenn man die 20 Gerichte bewertet hat eine Notification abschicken mit iwie "Wenn du exaktere Ergebnisse erhalten möchtest, kannst du hier $Link_zum_Speisplan weitere Gerichte bewerten"

2024-08-13 10:25 UTC, olech2412 commented on MensaHub-Models/src/main/java/de/olech2412/mensahub/models/authentification/MailUser.java
Resolved da angehoben auf 2.1.3

2024-08-13 15:14 UTC, whosFritz commented on MensaHub-Junction/pom.xml
> +        <!-- Vaadin Addons -->
hab ich gelöscht. war zu viel bloat. vielleicht probier ich es später nochmal

2024-08-13 15:16 UTC, whosFritz commented on MensaHub-Junction/src/main/java/de/olech2412/mensahub/junction/gui/views/NewsletterView.java
> +                                "Diese Empfehlungen basieren auf deinem bisherigen Essverhalten und deinen Vorlieben. " +
gefixed

2024-08-14 11:25 UTC, whosFritz commented
ActivationView:

Buttons fürs skippen sind nun über der MealBox -> responsive

2024-08-14 14:48 UTC, whosFritz commented
Passt so?

2024-08-14 14:53 UTC, whosFritz commented
Geh ich bin bei d Na d BL d ja e voll fne CNN MC CNN BC ja d CL f KV von oh go t no Don he no s kg or for dn

![static-assets-upload1087823629226472213](https://github.com/user-attachments/assets/bddd4c4a-4963-4d49-be9e-f810a66e89ab)

2024-08-14 14:53 UTC, whosFritz commented
sql wird wann anders angeschaut

2024-08-14 15:26 UTC, olech2412 approved these changes

2024-08-14 15:33 UTC, merged